apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microservices-swimlane
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - env: env0
      - env: env8
  template:
    metadata:
      name: '{{env}}-apps'
    spec:
      project: default
      source:
        repoURL: https://github.com/bxl1015/gitops-lane-sim.git # 请根据实际仓库地址修改
        targetRevision: main
        path: 'k8s/{{env}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
